name: Change Proposal
description: File a XLIFF specification change proposal
title: "[Proposal] <title>"
labels: [change proposal]
body:
- type: input
    id: authors
    label: Authors
    description: List authors of this proposal
- type: checkbox
    attributes:
      label: Target Specification
      description: Check all applicable specification types
      options:
        - XLIFF core specification
        - XLIFF extended specification
- type: checkbox
    attributes:
      label: Area of Changes
      description: Check all applicable change areas affected by this proposal
      options:
        - XLIFF specification document
        - XLIFF schema
        - XLIFF validator
        - Example files
- type: textarea
    id: proposal-description
    label: Detailed Description
    description: Describe the change proposal in detail
- type: textarea
    id: compatibility
    label: Compatibility Impacts
    description: Describe any potential compatibility issues affectign existing users and tools
